<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Headless" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageVersion Include="ColorTextBlock.Avalonia" Version="12.0.0-a3" />
    <PackageVersion Include="DiffPlex" Version="1.9.0" />
    <PackageVersion Include="Markdown.Avalonia" Version="12.0.0-a3" />
    <PackageVersion Include="Material.Icons" Version="3.0.2" />
    <PackageVersion Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageVersion Include="TUnit" Version="1.61.38" />
    <PackageVersion Include="XenoAtom.Terminal.UI" Version="3.8.1" />
    <PackageVersion Include="XenoAtom.Terminal.UI.Extensions.Markdown" Version="3.8.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>
</Project>
