<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DiffPlex" Version="1.9.0" />
    <PackageVersion Include="TUnit" Version="1.61.38" />
    <PackageVersion Include="XenoAtom.Terminal.UI" Version="3.8.1" />
    <PackageVersion Include="XenoAtom.Terminal.UI.Extensions.Markdown" Version="3.8.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>
</Project>
