<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DiffPlex" Version="1.9.0" />
    <PackageVersion Include="Terminal.Gui" Version="2.4.17" />
    <PackageVersion Include="Terminal.Gui.Editor" Version="2.5.7" />
    <PackageVersion Include="TUnit" Version="1.61.38" />
  </ItemGroup>
</Project>
