<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffPlex" />
    <PackageReference Include="Terminal.Gui" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhiAgent\PhiAgent.csproj" />
    <ProjectReference Include="..\PhiProvider\PhiProvider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PhiCoding.Tests" />
  </ItemGroup>

</Project>