using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization.Metadata;

namespace PhiAgent;

/// <summary>
/// Base class for tools whose parameters are a typed record. Provides the
/// schema (<see cref="Parameters"/>, generated by <c>PhiSchemaGen</c>) and
/// strict deserialization of raw JSON arguments into <typeparamref name="TArgs"/>
/// (case-insensitive, rejects unknown fields), then delegates to
/// <see cref="ExecuteTypedAsync"/>. Structured validation errors are
/// surfaced as <c>IsError: true</c> results so the LLM can retry.
/// <para>
/// <see cref="ArgsTypeInfo"/> supplies the <see cref="JsonTypeInfo{TArgs}"/>
/// from a source-generated context (required for NativeAOT).
/// </para>
/// </summary>
public abstract class TypedTool<TArgs> : Tool
{
    /// <summary>
    /// Source-generated JSON metadata for <typeparamref name="TArgs"/>.
    /// Subclasses supply this from their own <c>JsonSerializerContext</c>
    /// (e.g. <c>PhiCoding.ToolArgsJsonContext</c>), keeping this base class
    /// free of any application-layer dependency.
    /// </summary>
    protected abstract JsonTypeInfo<TArgs> ArgsTypeInfo { get; }

    public abstract Task<ToolResult> ExecuteTypedAsync(TArgs args, CancellationToken cancellationToken);

    /// <summary>
    /// Deserializes raw JSON arguments and delegates to
    /// <see cref="ExecuteTypedAsync"/>, surfacing validation errors as
    /// <c>IsError: true</c> results so the LLM can retry.
    /// </summary>
    public override async Task<ToolResult> ExecuteAsync(
        string toolName,
        string toolCallId,
        JsonObject arguments,
        CancellationToken cancellationToken)
    {
        try
        {
            var args = arguments.Deserialize(ArgsTypeInfo)
                ?? throw new JsonException("Arguments deserialized to null");
            return await ExecuteTypedAsync(args, cancellationToken);
        }
        catch (JsonException ex)
        {
            var path = string.IsNullOrEmpty(ex.Path) ? "(root)" : ex.Path;
            return new ToolResult(
                [new TextBlock(
                    $"Tool '{Name}' validation error at {path}: {ex.Message}")],
                IsError: true);
        }
    }

    /// <summary>
    /// Convenience overload for callers that don't track the tool name
    /// separately (the base name is used for error messages).
    /// </summary>
    public Task<ToolResult> ExecuteAsync(
        string toolCallId,
        JsonObject arguments,
        CancellationToken cancellationToken = default)
        => ExecuteAsync(Name, toolCallId, arguments, cancellationToken);
}
