using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Phi.SchemaGen;

/// <summary>
/// Source generator that emits the <c>Tool</c> property (with its JSON
/// schema) for every <c>TypedTool&lt;TArgs&gt;</c> subclass. Replaces the
/// runtime reflection in <c>Phi.TypedSchema</c>, which is incompatible
/// with NativeAOT (trimmed reflection returns an empty schema).
/// <para>
/// Generated schema construction uses only string-keyed
/// <c>JsonObject</c>/<c>JsonArray</c> APIs (AOT-safe) and mirrors the old
/// reflection shape: camelCase property names, <c>required</c> members, and
/// <c>[Description]</c> attributes. Nested record types get their own
/// <c>Build&lt;Name&gt;Schema()</c> helper method.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ToolSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tools = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { BaseList: not null } cds
                && cds.Modifiers.Any(SyntaxKind.PartialKeyword),
            static (ctx, _) => (INamedTypeSymbol?)ctx.SemanticModel.GetDeclaredSymbol(
                (ClassDeclarationSyntax)ctx.Node))
            .Where(static s => s is not null && IsTypedToolSubclass(s));

        context.RegisterSourceOutput(tools.Collect(), static (spc, toolSymbols) =>
        {
            foreach (var tool in toolSymbols)
            {
                var source = BuildToolSource(tool!);
                var hint = $"{tool!.ToDisplayString().Replace('.', '_').Replace('<', '_').Replace('>', '_')}.g.cs";
                spc.AddSource(hint, SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static bool IsTypedToolSubclass(INamedTypeSymbol type)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (current.OriginalDefinition.MetadataName == "TypedTool`1"
                && current.ContainingNamespace.ToDisplayString() == "Phi.Agent")
                return true;
        }
        return false;
    }

    private static INamedTypeSymbol FindArgsType(INamedTypeSymbol tool)
    {
        for (var current = tool.BaseType; current is not null; current = current.BaseType)
        {
            if (current.OriginalDefinition.MetadataName == "TypedTool`1"
                && current.ContainingNamespace.ToDisplayString() == "Phi.Agent"
                && current.TypeArguments.Length == 1
                && current.TypeArguments[0] is INamedTypeSymbol arg)
                return arg;
        }
        throw new InvalidOperationException("TypedTool<TArgs> args type not found");
    }

    private static string BuildToolSource(INamedTypeSymbol tool)
    {
        var args = FindArgsType(tool);

        // Collect every reachable nested object type (e.g. EditArgs -> EditOp)
        // so we can emit one schema helper per type.
        var nestedTypes = new List<INamedTypeSymbol>();
        var seen = new HashSet<string>();
        CollectNestedTypes(args, nestedTypes, seen);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Phi.Agent;");
        sb.AppendLine("using System.Text.Json.Nodes;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();
        sb.AppendLine($"namespace {tool.ContainingNamespace.ToDisplayString()};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {tool.Name}");
        sb.AppendLine("{");
        sb.AppendLine("    public override JsonObject Parameters => BuildSchema();");
        sb.AppendLine();
        sb.AppendLine($"    protected override JsonTypeInfo<{args.Name}> ArgsTypeInfo =>");
        sb.AppendLine($"        Phi.ToolArgsJsonContext.Default.{args.Name};");
        sb.AppendLine();
        sb.AppendLine("    private static JsonObject BuildSchema() => BuildObjectSchema();");
        sb.AppendLine();
        sb.AppendLine("    private static JsonObject WithDescription(JsonObject schema, string description)");
        sb.AppendLine("    {");
        sb.AppendLine("        schema[\"description\"] = description;");
        sb.AppendLine("        return schema;");
        sb.AppendLine("    }");

        // The args type's own helper is the entry point referenced by
        // BuildSchema.
        sb.AppendLine();
        AppendObjectSchemaHelper(sb, args, "BuildObjectSchema");

        // One helper per nested type.
        foreach (var nested in nestedTypes)
        {
            sb.AppendLine();
            AppendObjectSchemaHelper(sb, nested, $"Build{nested.Name}Schema");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void CollectNestedTypes(
        INamedTypeSymbol type,
        List<INamedTypeSymbol> nested,
        HashSet<string> seen)
    {
        foreach (var prop in PublicProperties(type))
        {
            var t = UnwrapNullable(prop.Type);
            if (t is IArrayTypeSymbol arr)
            {
                var element = UnwrapNullable(arr.ElementType);
                if (element is INamedTypeSymbol cls && IsNestedObjectType(cls))
                    AddNested(cls);
                continue;
            }
            if (t is INamedTypeSymbol named && IsNestedObjectType(named))
                AddNested(named);
        }

        void AddNested(INamedTypeSymbol cls)
        {
            if (!seen.Add(cls.ToDisplayString())) return;
            nested.Add(cls);
            // Recurse for nested-of-nested.
            CollectNestedTypes(cls, nested, seen);
        }
    }

    private static bool IsNestedObjectType(INamedTypeSymbol t) =>
        t.SpecialType == SpecialType.None
        && t.TypeKind == TypeKind.Class;

    private static void AppendObjectSchemaHelper(StringBuilder sb, INamedTypeSymbol type, string helperName)
    {
        sb.AppendLine($"    private static JsonObject {helperName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        var schema = new JsonObject();");
        sb.AppendLine("        schema[\"type\"] = \"object\";");
        sb.AppendLine("        var properties = new JsonObject();");

        var required = new List<string>();
        foreach (var prop in PublicProperties(type))
        {
            var name = ToCamelCase(prop.Name);
            var desc = GetDescription(prop);

            var schemaExpr = BuildPropertySchemaExpr(prop, desc);

            sb.AppendLine($"        properties[\"{name}\"] = {schemaExpr};");

            if (IsRequired(prop)) required.Add(name);
        }

        sb.AppendLine("        schema[\"properties\"] = properties;");
        sb.AppendLine("        var requiredList = new JsonArray();");
        foreach (var name in required)
            sb.AppendLine($"        requiredList.Add((JsonNode)\"{name}\");");
        sb.AppendLine("        schema[\"required\"] = requiredList;");
        sb.AppendLine("        return schema;");
        sb.AppendLine("    }");
    }

    private static string BuildPropertySchemaExpr(IPropertySymbol prop, string? description)
    {
        var t = UnwrapNullable(prop.Type);
        string baseExpr;
        if (t is IArrayTypeSymbol arr)
        {
            var element = UnwrapNullable(arr.ElementType);
            var itemExpr = BuildSimpleTypeExpr(element)
                ?? (element is INamedTypeSymbol namedElement && IsNestedObjectType(namedElement)
                    ? $"Build{namedElement.Name}Schema()"
                    : "new JsonObject { [\"type\"] = \"object\" }");
            baseExpr = $"new JsonObject {{ [\"type\"] = \"array\", [\"items\"] = {itemExpr} }}";
        }
        else
        {
            baseExpr = BuildSimpleTypeExpr(t)
                ?? (t is INamedTypeSymbol named && IsNestedObjectType(named)
                    ? $"Build{named.Name}Schema()"
                    : "new JsonObject { [\"type\"] = \"object\" }");
        }
        return description is not null
            ? $"WithDescription({baseExpr}, \"{Escape(description)}\")"
            : baseExpr;
    }

    private static string? BuildSimpleTypeExpr(ITypeSymbol t)
    {
        if (t.SpecialType == SpecialType.System_String) return "new JsonObject { [\"type\"] = \"string\" }";
        if (t.SpecialType == SpecialType.System_Boolean) return "new JsonObject { [\"type\"] = \"boolean\" }";
        if (t.SpecialType is SpecialType.System_Byte or SpecialType.System_SByte
            or SpecialType.System_Int16 or SpecialType.System_UInt16
            or SpecialType.System_Int32 or SpecialType.System_UInt32
            or SpecialType.System_Int64 or SpecialType.System_UInt64)
            return "new JsonObject { [\"type\"] = \"integer\" }";
        if (t.SpecialType is SpecialType.System_Single or SpecialType.System_Double
            or SpecialType.System_Decimal)
            return "new JsonObject { [\"type\"] = \"number\" }";
        return null;
    }

    private static IEnumerable<IPropertySymbol> PublicProperties(INamedTypeSymbol type)
    {
        foreach (var prop in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public) continue;
            if (prop.IsStatic || prop.IsIndexer) continue;
            if (prop.GetMethod is null) continue;
            yield return prop;
        }
    }

    private static ITypeSymbol UnwrapNullable(ITypeSymbol t) =>
        t is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && named.TypeArguments.Length == 1
            ? named.TypeArguments[0]
            : t;

    private static string? GetDescription(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString()
                    == "System.ComponentModel.DescriptionAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is string s)
                return s;
        }
        return null;
    }

    private static bool IsRequired(IPropertySymbol prop)
    {
        if (prop.IsRequired) return true;
        return prop.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.RequiredMemberAttribute");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name) || !char.IsUpper(name[0])) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
}
