using System.ComponentModel;
using Phi.Agent;

namespace Phi.Extensions.HelloTool;

/// <summary>
/// Arguments for the <see cref="HelloTool"/>. Mirrors the BashTool /
/// ReadTool pattern from CodingPack: a typed record (instead of a hand-
/// rolled <c>JsonObject</c>) so the JSON schema and the
/// <see cref="System.Text.Json.Serialization.Metadata.JsonTypeInfo{T}"/>
/// are source-generated by <c>Phi.SchemaGen</c> (NativeAOT-safe; no
/// reflection at runtime).
/// <para>
/// <see cref="Who"/> is optional (no <c>required</c> keyword, nullable) —
/// when the model omits it, <see cref="HelloTool.ExecuteTypedAsync"/>
/// falls back to <c>"world"</c>.
/// </para>
/// </summary>
public sealed record HelloArgs
{
    [Description("Name to greet. Defaults to \"world\" when omitted.")]
    public string? Who { get; init; }
}

/// <summary>
/// Sprint 1 reference tool: greets <c>args.Who</c> (or <c>"world"</c> when
/// omitted). Inherits <see cref="TypedTool{TArgs}"/> so the
/// <c>Parameters</c> schema and the strict args deserializer are
/// source-generated by <c>Phi.SchemaGen</c> — no hand-maintained
/// <c>JsonObject</c>, no manual <c>arguments["who"]?.GetValue&lt;string&gt;()</c>.
/// </summary>
public sealed partial class HelloTool : TypedTool<HelloArgs>
{
    public override string Name => "hello";

    public override string Description =>
        "Greet someone by name. Returns a friendly one-line greeting.";

    public override async Task<ToolResult> ExecuteTypedAsync(
        HelloArgs args,
        CancellationToken cancellationToken)
    {
        var who = string.IsNullOrWhiteSpace(args.Who) ? "world" : args.Who;
        // Simulate tiny async work so cancellation is testable (Sprint 2+).
        await Task.Yield();
        return new ToolResult(
            [new TextBlock($"Hello, {who}!")],
            IsError: false);
    }
}

/// <summary>
/// Reference extension: registers <see cref="HelloTool"/> via
/// <see cref="IPhiApi.RegisterTool"/> + a <c>ToolContribution</c> snippet
/// for the system prompt. Demonstrates the minimal contract extension
/// authors must satisfy and validates that the
/// <c>Phi.Extensions.Host</c> pipeline (load → setup → register tool →
/// invoke) works end-to-end.
/// </summary>
[PhiExtension(
    Name = "hello-tool",
    Version = "1.0.0",
    Description = "Greet someone by name.",
    Capabilities = ExtensionCapability.TranscriptWrite)]
public sealed class HelloToolExt : IPhiExtension
{
    public void Setup(IPhiApi api)
    {
        var hello = new HelloTool();
        api.RegisterTool(
            hello,
            new ToolContribution
            {
                Tool = hello,
                PromptSnippet = "hello: Greet someone by name.",
                PromptGuidelines = ["Use hello when asked to greet someone."],
            });

        api.AddPromptGuideline("When the user says hi, greet them back with hello(\"world\").");

        // Sprint 4.5: extension slash commands are dispatched by the TUI's
        // PromptInput after the built-in switch misses. The handler here
        // submits a user message that greets the person (mirroring what the
        // model would do if it had invoked the hello tool itself).
        api.RegisterCommand(
            "/hello",
            (args, _) =>
            {
                var who = string.IsNullOrWhiteSpace(args) ? "world" : args;
                api.SubmitUserMessage($"Say hello to {who}");
                return $"hello {who}";
            },
            description: "Say hello to someone.",
            usage: "/hello [name]",
            aliases: ["/hi"]);
    }
}
